name: run terraform plan on pull request
run-name: ${{ github.head_ref }} pull request by ${{ github.actor }}

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: read

jobs:
  plan-terraform-changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::664047078509:role/ianb-github-actions-role
          aws-region: eu-west-2
          audience: sts.amazonaws.com

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out .plan

      - name: Post PR comment
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ github.token }}
          planfile: .plan

      